### ISSUE TITLE
Definition to-do's

### ISSUE THREAD

**Issue by jmeas** [jmeas/api-pls#193]
These Resource Definitions should enable me to clean up this code quite a bit. Here's a short list of to-do's.

- [x] use data in Definition as the source of truth for anything name-related in SQL builders. Nothing should be hardcoded in the SQL builder itself.
- [x] refactor normalized model to keep built_in_meta separate. this will break a lot of things.
- [x] namespace raw/escaped values under the type of thing that it is. i.e. `tableName.raw` and `tableName.escaped`
- [x] Store useful maps of things:
  - [ ] ~~all column names~~ wouldn't be used I think
  - [x] attrs, relationships, meta
- [x] update the SQL builders to use all of this data, and to compute nothing
- [x] reorganize everything!
- [x] tests for new utilities
