### ISSUE TITLE
JSON API Compliance Checklist

### ISSUE THREAD

**Issue by jmeas** [jmeas/api-pls#75]
This is an incomplete checklist of how incomplete my compliance with JSON API is.

- [x] attributes (CRUD)
- [x] meta attributes (CRUD)
- [ ] relations
  - [ ] many-to-one
  - [ ] many-to-many
  - [ ] one-to-one
  - [ ] relationship endpoints `/v1/:resource/relationships/:related`
  - [ ] related endpoints `/v1/:resource/:related`
- [x] standard errors
- [ ] sparse fieldsets
- [ ] sorting
- [ ] pagination
- [ ] filtering
- [ ] links

**Comment by jmeas** [comment]
Moved this list to the README for greater visibility
